Updated example config to use recommended settings instead of defaul,…
cognitedata/inso-bootstrap-cli pull request #43
Opened 2022-05-16 12:50 UTC by sdorheim

… rewrote a bit and added sections to the Readme

2022-05-29 18:53 UTC, spex66 requested changes

2022-05-29 19:23 UTC, sdorheim commented on README.md
>  - [InSo Bootstrap CLI](#inso-bootstrap-cli)
@spex66, is there a tool to update or just manual procedure?

2022-05-29 19:24 UTC, sdorheim commented on README.md
> +To start you have to install Poetry, a tool to manage python dependencies and virtual environments. It is recommended running this on Linux, WSL2 or Mac.
I took it from our internal Python-setup guide, but I agree, will change

2022-05-30 12:03 UTC, sdorheim commented on README.md
> +
This has been fixed now

2022-05-30 12:03 UTC, sdorheim commented on .env_example
> +BOOTSTRAP_CDF_HOST=https://<Cluster Id>.cognitedata.com
This has been updated

2022-05-30 12:03 UTC, sdorheim commented on README.md
>  - [InSo Bootstrap CLI](#inso-bootstrap-cli)
Done

2022-05-30 12:03 UTC, sdorheim commented on README.md
> +          # "yes"|"no" deploy with special groups and aad_mappings
Done

2022-05-30 12:06 UTC, sdorheim commented on README.md
Done

2022-05-30 12:06 UTC, sdorheim commented on README.md
> +poetry run bootstrap-cli --debug prepare --aad-source-id <idb-source-id>
done

2022-05-30 13:44 UTC, spex66 approved these changes
thx for the effort
some final changes (cleanup and renamed `configs/` examples)

2022-05-30 13:45 UTC, merged